name: Terraform CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  plan:
    name: Plan (Terraform Cloud)
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
          # This writes ~/.terraform.d/credentials.tfrc.json for app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_app_terraform_io }}

      # # Install local modules/providers so validate works offline
      # #- name: Terraform Init (backendless for validate)
      #  # run: terraform init -backend=false -input=false

      # - name: Terraform Fmt (auto-fix)
      #   run: terraform fmt -recursive

      # - name: Terraform Fmt Check
      #   run: terraform fmt -check -recursive

      # - name: Terraform Validate
      #   run: terraform validate -no-color

      # Real init against your Terraform Cloud remote backend
      - name: Terraform Init (remote backend)
        run: terraform init -reconfigure -input=false

      # Triggers remote plan in Terraform Cloud (you'll Confirm & Apply in TFC)
      - name: Terraform Plan (remote in TFC)
        run: terraform plan -no-color -input=false
